language: c
install:
  # vim-common is for xxd
- sudo apt-get install -qq libfuse-dev pkg-config fuse user-mode-linux
- sudo mknod /dev/fuse c 10 229
- sudo chmod 666 /dev/fuse
- make
script: ./umltest.sh

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "FWSmky2f3XLHj71JTqj0uaaJZ+seq6CzblIbR7j76wDj4JwL6SAYeqtw9gXpcpVVwtCFlmKFAHCVmCpgzpP2wI9ryGuW1KCgMqK6EA8mRmhuMn7mTWdyaLSDWh6YAGO+672SK6CPmEYbxDarX6uDlMnFt7dCHIwDTVJF+2EfHDg="



addons:
  coverity_scan:
    project:
      name: "vi/execfuse"
      description: "Build submitted via Travis CI"
    notification_email: vi0oss@gmail.com
    build_command_prepend: "true"
    build_command:   "make -B -j 4"
    branch_pattern: coverity_scan
