language: c
install:
  # vim-common is for xxd
- sudo apt-get install -qq libfuse-dev pkg-config fuse
- make
script: ./tests.sh

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - "M3+qE05xL5qpu3pvNsCL/2TxFOtM/CCr4XKHiQ4B2GkDVq6JmIcLEjs23PObCO87OzpczFcGC4RT1Q7QY+MMpsEhcPRAKUH67zxJFjILHWB0uUqwP7R0RK2o/YE1RcD3265sTe5gWespp7wXVTQHS46TDm+T8JDZdel+mhkawIY="


addons:
  coverity_scan:
    project:
      name: "vi/execfuse"
      description: "Build submitted via Travis CI"
    notification_email: vi0oss@gmail.com
    build_command_prepend: "true"
    build_command:   "make -B -j 4"
    branch_pattern: coverity_scan
